name: API CI/CD Workflow
on:
    push:
        branches:
            # - "NA"
            - "dev/updates"

jobs:
    # build a single image
    buildImage:
        name: "Build Image"
        uses: ./.github/workflows/container-build-template.yml
        secrets: inherit

    # deploy the image to cluster 1
    deployGreen:
        needs: [buildImage]
        name: "Deploy to Green Cluster"
        uses: ./.github/workflows/container-deploy-template.yml
        with:
            cluster: green
            imageTag: ${{ needs.buildImage.outputs.shaTag }}
        secrets: inherit

    # deploy the image to cluster 2
    deployBlue:
        needs: [buildImage]
        name: "Deploy to Blue Cluster"
        uses: ./.github/workflows/container-deploy-template.yml
        with:
            cluster: blue
            imageTag: ${{ needs.buildImage.outputs.shaTag }}
        secrets: inherit
